apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "riskmanagement.backendName" . }}-config
  labels:
    {{- include "riskmanagement.labels" . | nindent 4 }}
data:
  DB_URL: {{ default (printf "jdbc:postgresql://%s:%v/postgres?stringtype=unspecified&sslmode=disable&currentSchema=riskmanagement" (include "riskmanagement.postgresName" .) .Values.postgres.service.port) .Values.backend.env.dbUrl | quote }}
  ALLOWED_ORIGINS: {{ .Values.backend.env.allowedOrigins | quote }}
  SEED_ENABLED: {{ .Values.backend.env.seedEnabled | quote }}
  SEED_RESET_BEFORE_SEED: {{ .Values.backend.env.seedResetBeforeSeed | quote }}
