apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: riskmanagement
data:
  DB_URL: jdbc:postgresql://postgres:5432/postgres?stringtype=unspecified&sslmode=disable&currentSchema=riskmanagement
  ALLOWED_ORIGINS: http://localhost,http://localhost:4200
  SEED_ENABLED: "true"
  SEED_RESET_BEFORE_SEED: "false"
